[workspace]
members = [
    "erc20"
]

[workspace.dependencies]
prost = "0.11"
prost-types = "0.11"
substreams = "0.5"
substreams-ethereum = "0.9"
substreams-entity-change = "1.0.0"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"